
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { MessageSquare, Send, Book, PlusCircle, Plus, Loader2, FileText, Input } from 'lucide-react';
import { format } from 'date-fns';

import { PageHeader } from '@/components/page-header';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import History from '@/app/componentsV2/ui/history';


const mockHistory = [
  {
    id: 'chat1',
    book: 'Oliver English Class 05',
    date: new Date('2025-10-14'),
    lastMessage: 'Sure, I can explain the main character...',
    messages: [
      { role: 'assistant', content: `Hello! How can I help you with "Oliver English Class 05" today?` },
      { role: 'user', content: 'Can you tell me about the main character?' },
      { role: 'assistant', content: 'Sure, I can explain the main character...' },
    ]
  },
  {
    id: 'chat2',
    book: 'The Great Gatsby',
    date: new Date('2025-10-12'),
    lastMessage: 'It symbolizes the American Dream.',
    messages: [
      { role: 'assistant', content: `Hello! How can I help you with "The Great Gatsby" today?` },
      { role: 'user', content: 'What is the green light?' },
      { role: 'assistant', content: 'It symbolizes the American Dream.' },
    ]
  },
];

const mockBooks = [
  'Oliver English Class 05',
  'The Great Gatsby',
  'Introduction to Algebra',
  'A Brief History of Time',
];

const ChatMessage = ({
  role,
  content,
  isLoading = false,
}) => {
  console.log(content);
  const isUser = role === 'user';
  return (
    <div
      className={cn(
        'flex items-start gap-3',
        isUser ? 'justify-end' : 'justify-start'
      )}
    >
      {!isUser && (
        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center text-white text-sm font-semibold flex-shrink-0">
          AI
        </div>
      )}
      <div className="bg-gradient-to-br from-primary to-accent rounded-2xl rounded-tr-sm p-4 max-w-[80%]">

        {isLoading ? (
          <div className="space-y-2">
            <Skeleton className="h-3 w-40" />
            <Skeleton className="h-3 w-32" />
          </div>
        ) : (
          <p>{content}</p>
        )}
      </div>
      {isUser && (
        <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-foreground text-sm font-semibold flex-shrink-0">
          U
        </div>
      )}
    </div>
  )
};

function ChatInterface({ chatSession, setChatSession }) {
  const [messages, setMessages] = useState(chatSession.messages);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSendMessage = (e) => {
    e.preventDefault();
    if (!input.trim()) return;

    const newMessages = [...messages, { role: 'user', content: input }];
    setMessages(newMessages);
    setInput('');
    setIsLoading(true);

    // Mock AI response
    setTimeout(() => {
      const response = {
        role: 'assistant',
        content: 'This is a mock response based on the book content. In a real application, this would be a dynamic answer generated by an AI model.',
      };
      const updatedMessages = [...newMessages, response]
      setMessages(updatedMessages);

      const updatedHistoryItem = {
        ...chatSession,
        messages: updatedMessages,
        lastMessage: response.content
      }
      const historyIndex = mockHistory.findIndex(h => h.id === chatSession.id);
      mockHistory[historyIndex] = updatedHistoryItem;

      setChatSession(updatedHistoryItem);
      setIsLoading(false);
    }, 1500);
  };

  return (
    <div className="lg:col-span-3">
      <div className="rounded-2xl border border-border bg-card shadow-[var(--shadow-md)] flex flex-col h-[600px]">
        {/* Chat Header */}
        <div className="p-6 border-b border-border">
          <div className="flex items-center gap-3">
            <MessageSquare className="h-5 w-5 text-primary" />
            <div>
              <h2 className="font-semibold text-lg">Chat with: {chatSession.book}</h2>
              <p className="text-sm text-muted-foreground">
                Engage in real-time conversations with your learning materials.
              </p>
            </div>
          </div>
        </div>

        {/* Messages */}
        <div className="flex-1 p-6 overflow-y-auto space-y-4">
          {messages.map((msg, index) => (
            <ChatMessage key={index} role={msg.role} content={msg.content} />
          ))}
          {isLoading && <ChatMessage role="assistant" isLoading />}
        </div>
        {/* Input Area */}
        <div className="p-6 border-t border-border">
          <div className="flex gap-3">
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask a question about the book..."
              // className="flex-1 resize-none"
              rows={1}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSendMessage(e);
                }
              }}
            />
            <Button className="bg-gradient-to-r from-primary to-accent hover:opacity-90 transition-opacity px-6">
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

function NewChatForm({ onStartChat }) {
  const [selectedBook, setSelectedBook] = useState(null);

  const handleStart = () => {
    if (selectedBook) {
      onStartChat(selectedBook);
    }
  }

  return (
    <div className="flex flex-col items-center justify-center min-h-[500px]">
      <div className="w-full max-w-md">
        <Card>
          <CardHeader className="text-center">
            <div className="flex justify-center mb-4">
              <Book className="h-10 w-10 text-primary" />
            </div>
            <h2 className="text-xl font-semibold">Start a New Chat</h2>
          </CardHeader>
          <CardContent className="flex flex-col items-center gap-4">
            <p className="text-sm text-muted-foreground text-center">Select a book to begin your conversation.</p>
            <Select onValueChange={setSelectedBook}>
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Choose a book" />
              </SelectTrigger>
              <SelectContent>
                {mockBooks.map((book) => (
                  <SelectItem key={book} value={book}>{book}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </CardContent>
          <CardFooter className="justify-center">
            <Button onClick={handleStart} className="w-full" disabled={!selectedBook}>
              <MessageSquare className="mr-2 h-4 w-4" /> Start Chat
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}

export default function ChatPage() {
  const [selectedChat, setSelectedChat] = useState(mockHistory[0]);
  const [isLoading, setIsLoading] = useState(false);

  const handleStartChat = (book) => {
    setIsLoading(true);
    setSelectedChat(null);
    setTimeout(() => {
      const newChat = {
        id: `chat${mockHistory.length + 1}`,
        book,
        date: new Date(),
        lastMessage: `Hello! How can I help you with "${book}" today?`,
        messages: [{ role: 'assistant', content: `Hello! How can I help you with "${book}" today?` }]
      };
      mockHistory.unshift(newChat);
      setSelectedChat(newChat);
      setIsLoading(false);
    }, 1000);
  }

  return (
    <div className="max-w-7xl mx-auto my-5 space-y-6">
      <div className="relative overflow-hidden rounded-3xl border border-border bg-gradient-to-br from-primary/10 via-accent/10 to-primary/5 p-8 shadow-[var(--shadow-lg)]">
        <div className="relative flex items-center gap-4">
          <div className="p-3 rounded-xl bg-gradient-to-br from-primary to-accent shadow-[var(--shadow-glow)]">
            <FileText className="h-8 w-8 text-white" />
          </div>
          <div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
              Chat with Book
            </h1>
            <p className="text-muted-foreground mt-1 text-lg">
              Engage in real-time conversations with your learning materials.
            </p>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* {History} */}
        <History
          selectedItem={selectedChat}
          setSelectedItem={setSelectedChat}
          historyData={mockHistory}
        />
        {/* Lesson Plan Content */}
        {isLoading ? (
          <div className="flex items-center justify-center h-full">
            <div className="text-center">
              <Loader2 className="mx-auto h-12 w-12 animate-spin text-primary mb-4" />
              <h3 className="text-lg font-medium text-foreground">Starting new chat...</h3>
              <p className="text-sm text-muted-foreground">
                Please wait a moment.
              </p>
            </div>
          </div>
        ) : selectedChat ? (
          <ChatInterface chatSession={selectedChat} setChatSession={setSelectedChat} />
        ) : (
          <NewChatForm onStartChat={handleStartChat} />)}
      </div>
    </div>
  )
  return (
    <div className="grid grid-cols-1 md:grid-cols-[300px_1fr] h-full">
      <div className="hidden md:flex flex-col border-r bg-muted/20 p-4 space-y-4">
        <Button variant="outline" onClick={() => setSelectedChat(null)}>
          <Plus className="mr-2" /> New Chat
        </Button>
        <div className="flex-1 overflow-y-auto">
          <h3 className="text-xs font-semibold uppercase text-muted-foreground tracking-wider px-2 mb-2">
            Chat History
          </h3>
          <div className="space-y-2">
            {mockHistory.map((item) => (
              //   <History
              //   key={item.id}
              //   item={item}
              //   selectedItem={selectedChat}
              //   setSelectedItem={selectedChat}
              // />
              <button
                key={item.id}
                onClick={() => setSelectedChat(item)}
                className={cn(
                  'w-full text-left p-2 rounded-lg border',
                  selectedChat?.id === item.id
                    ? 'bg-primary/10 border-primary'
                    : 'hover:bg-muted/50'
                )}
              >
                <div className="flex justify-between items-center text-xs text-muted-foreground mb-1">
                  <MessageSquare className="w-4 h-4 text-blue-500" />
                  <span>{format(item.date, 'dd/MM/yyyy')}</span>
                </div>
                <p className="font-semibold text-sm truncate">{item.book}</p>
                <p className="text-xs text-muted-foreground truncate">
                  {item.lastMessage}
                </p>
              </button>
            ))}
          </div>
        </div>
      </div>

      <main className="p-6">
        {isLoading ? (
          <div className="flex items-center justify-center h-full">
            <div className="text-center">
              <Loader2 className="mx-auto h-12 w-12 animate-spin text-primary mb-4" />
              <h3 className="text-lg font-medium text-foreground">Starting new chat...</h3>
              <p className="text-sm text-muted-foreground">
                Please wait a moment.
              </p>
            </div>
          </div>
        ) : selectedChat ? (
          <ChatInterface chatSession={selectedChat} setChatSession={setSelectedChat} />
        ) : (
          <NewChatForm onStartChat={handleStartChat} />
        )}
      </main>
    </div>
  );
}
